CREATE TABLE ALUNO (
	ID INT IDENTITY,
	NOME VARCHAR (30) NOT NULL,  
	EMAIL VARCHAR (50) NOT NULL,
	CELULAR VARCHAR(20) NOT NULL,
	RA TINYINT NOT NULL,
	FOTO VARCHAR(255),
	
	CONSTRAINT PK_ALUNO PRIMARY KEY(ID),
	CONSTRAINT UQ_EMAIL_ALUNO UNIQUE (EMAIL),
	CONSTRAINT UQ_CELULAR_ALUNO UNIQUE (CELULAR)
);

CREATE TABLE PROFESSOR(
	ID INT IDENTITY,
	EMAIL VARCHAR (50) NOT NULL,
	CELULAR VARCHAR (20) NOT NULL, 
	APELIDO VARCHAR (30),

	CONSTRAINT PK_PROFESSOR PRIMARY KEY (ID),
	CONSTRAINT UQ_EMAIL_PROFESSOR UNIQUE (EMAIL),
	CONSTRAINT UQ_CELULAR_PROFESSOR UNIQUE (CELULAR)
);


CREATE TABLE CURSO(
	ID INT IDENTITY,
	NOME VARCHAR (30) NOT NULL,

	CONSTRAINT PK_CURSO PRIMARY KEY (ID),
	CONSTRAINT UQ_NOME_CURSO UNIQUE (NOME)
);


